### PR TITLE
Add a translation file for the GUI, mark (un)translatable content properly

### PR DESCRIPTION
**Pull request by xavery**
This cannot be merged until [issue 2 in justdan96/tsmuxer_build ](https://github.com/justdan96/tsmuxer_build/issues/2) is resolved, otherwise build issues in nightlies will occur.

### CODE REVIEW

**Comment by justdan96** [comment]
Blocked until I resolve the issue in the Docker container.

**Comment by justdan96** [comment]
One thing I noticed - after a build the file tsMuxerGUI/translations/tsmuxergui_en.ts is created. Should we add *.ts to the .gitignore file?

**Comment by xavery** [comment]
Works great with the latest Docker image update - do you have any objections about merging this?

**Comment by justdan96** [comment]
No, would be eager to see a first translation added in a subsequent PR so people can get a good idea of how they can contribute translations.

**Comment by abakum** [comment]
image
That's right?

**Comment by xavery** [comment]
@abakum Yes, fantastic!

**Comment by abakum** [comment]
https://github.com/justdan96/tsMuxer/pull/217

**Pull request merged**
