### PR TITLE
Now the tsMuxeR requires .meta in utf8

### PR DESCRIPTION
**Pull request by abakum**
Thanks, @xavery  for unicode

### CODE REVIEW

**Comment by justdan96** [comment]
What exactly was the format that the meta file was in before? I thought it was ASCII

**Comment by xavery** [comment]
The encoding of the meta file was actually dependent on the code page of the computer where the program was running - talking about Windows, of course. Both Linux and MacOS have always used UTF-8 in this regard.

**Comment by justdan96** [comment]
Ah of course. Maybe we can tighten up the wording to say it only affects Windows?

**Comment by xavery** [comment]
Yup. I'll push some wording fixes and merge this later on.

**Comment by abakum** [comment]
Great, then I close this request

**Pull request closed without merging**
