### PR TITLE
Allow UHD BD version 3

### PR DESCRIPTION
**Pull request by jcdr428**

### CODE REVIEW

**Comment by jcdr428** [comment]
The four commits should be merged.
The patch allows to have all versions "0200" in .clpi, .mpls and .bdmv files changed to "0300", simply by changing "--bluray" to "--bluray v3" in the meta file.
There will need to be a check box added in the GUI to include this option.

**Comment by justdan96** [comment]
I have created a new branch which merges all your pull requests. I will pull that branch to master once I have tested it. 

I really appreciate the contributions you are making to tsMuxer but if I could ask that in the future you merge all your changes into one branch and do a pull request against that it would make my job easier!

For reference here is what I ran to merge all your changes:
```
git checkout master
git pull
git fetch https://github.com/jcdr428/tsMuxer.git patch-7
git merge FETCH_HEAD
git fetch https://github.com/jcdr428/tsMuxer.git patch-8
git merge FETCH_HEAD
git fetch https://github.com/jcdr428/tsMuxer.git patch-9
git merge FETCH_HEAD
git fetch https://github.com/jcdr428/tsMuxer.git patch-10
git checkout -b enhancement-uhd-bd-v3
git add -A
git commit -m "..."
git push
```

**Comment by justdan96** [comment]
In the branch with these changes I changed the option from "--blu-ray v3" (space) to "--blu-ray-v3" to fit with how the other parameters are handled. I've also updated the usage information in the CLI and added the option to the GUI.

https://github.com/justdan96/tsMuxer/compare/enhancement-uhd-bd-v3

Can you please check if this branch works okay for you?

**Comment by jcdr428** [comment]
@justdan96 I confirm that the branch works ok !

**Comment by jcdr428** [comment]
@justdan96 actually, "--bluray v3" was working correctly, but with "--bluray-v3" the mpls files are not well formed. You also have to change line 1341 of tsMuxer.cpp to:
else if (paramPair[0] == "--blu-ray" || paramPair[0] == "--blu-ray-v3" || paramPair[0] == "--avchd") {

**Pull request closed without merging**
