### PR TITLE
Fix fps info

### PR DESCRIPTION
**Pull request by jcdr428**
Hopefully last bug on fps reading...

- correct text descriptions from sps and vps
- remove junk from metaDemuxer.cpp (calling getTrackFps which always sets fps to 0 !!)

### CODE REVIEW

**Comment by jcdr428** [comment]
Should fix #89.

**Comment by justdan96** [comment]
Has this been tested with a variety of sources, so we can check for regressions?

**Comment by jcdr428** [comment]
@justdan96 I've tested with five files: .mkv, .ts, .hevc, hevc .m2ts, avc .m2ts
fps was fixed on these five tests.

**Comment by xavery** [comment]
Wanted to merge this tonight, but I can't reproduce the issue no matter how hard I try. Let's wait until we get a reply on #89.

**Comment by jcdr428** [comment]
@xavery agreed. The two samples I was sent (from W10x64  users, same as me) didn't produce any issue, it is strange that the behavior is not consistent between PCs.
What is sure is that the part with "getTrackFps" may have been added by Roman between 2.6.12 and 2.6.15 but seems unfinished.
Muxing AV and srt into an mkv is the only way I found to produce the issue. So let's see what is the feedbak...

**Comment by jcdr428** [comment]
@xavery see my comment on issue #89: the bug comes from the decimal "comma" in the locale.
This fix #130 is still needed for hevc to work correctly.

**Comment by xavery** [comment]
GUI issue reproduced and fixed. Roman was trying too hard to do the right thing and it came back to bite us on the butt - in his credit, though, locale-dependent behaviour in text parsing functions changed a bit between Qt 4 and Qt 5. I'll prepare a bigger commit which hopefully cleans this up. For now, this solves the immediate issue.

**Pull request merged**
