### PR TITLE
Improve lisibility of console output in track detection mode

### PR DESCRIPTION
**Pull request by jcdr428**
Example, before patch:
```
File #00000 name=C:\MOVIE1\BDMV\STREAM\00027.m2ts
Duration: 00:00:55.054
start-time: 524280
Marks: 00:00:00.000

File #00001 name=C:\MOVIE1\BDMV\STREAM\00028.m2ts
Duration: 00:00:58.099
start-time: 524280
Marks: 00:01:16.201

File #00002 name=C:\MOVIE1\BDMV\STREAM\00000.m2ts
Duration: 00:06:03.237
start-time: 524280
Marks: 00:06:29.430

File #00003 name=C:\MOVIE1\BDMV\STREAM\00001.m2ts
Duration: 00:00:53.136
start-time: 524280

File #00004 name=C:\MOVIE1\BDMV\STREAM\00002.m2ts
Duration: 00:01:19.829
start-time: 524280
Marks: 00:09:22.895

File #00005 name=C:\MOVIE1\BDMV\STREAM\00005.m2ts
Duration: 00:00:19.811
start-time: 524280

File #00006 name=C:\MOVIE1\BDMV\STREAM\00008.m2ts
Duration: 00:00:28.903
start-time: 524280

File #00007 name=C:\MOVIE1\BDMV\STREAM\00009.m2ts
Duration: 00:00:25.984
start-time: 524280
Marks: 00:10:58.073

File #00008 name=C:\MOVIE1\BDMV\STREAM\00012.m2ts
Duration: 00:00:24.649
start-time: 524280

File #00009 name=C:\MOVIE1\BDMV\STREAM\00013.m2ts
Duration: 00:00:21.646
start-time: 524280

File #00010 name=C:\MOVIE1\BDMV\STREAM\00016.m2ts
Duration: 00:01:20.622
start-time: 524280

File #00011 name=C:\MOVIE1\BDMV\STREAM\00018.m2ts
Duration: 00:00:37.662
start-time: 524280
Marks: 00:13:30.976

File #00012 name=C:\MOVIE1\BDMV\STREAM\00021.m2ts
Duration: 00:28:00.136
start-time: 524280
Marks: 00:17:40.017 00:19:37.551 00:24:48.320 00:28:55.233 00:33:05.066
Marks: 00:38:13.416 00:40:33.138

File #00013 name=C:\MOVIE1\BDMV\STREAM\00017.m2ts
Duration: 00:00:18.935
start-time: 524280

File #00014 name=C:\MOVIE1\BDMV\STREAM\00033.m2ts
Duration: 00:26:22.831
start-time: 524280
Marks: 00:44:11.231 00:46:59.316 00:51:27.667 00:57:02.168 00:59:32.318
Marks: 01:00:53.524 01:07:19.743

File #00015 name=C:\MOVIE1\BDMV\STREAM\00034.m2ts
Duration: 00:00:24.566
start-time: 524280

File #00016 name=C:\MOVIE1\BDMV\STREAM\00049.m2ts
Duration: 00:02:42.912
start-time: 524280
Marks: 01:11:25.656

File #00017 name=C:\MOVIE1\BDMV\STREAM\00037.m2ts
Duration: 00:01:26.878
start-time: 524280

File #00018 name=C:\MOVIE1\BDMV\STREAM\00050.m2ts
Duration: 00:02:03.331
start-time: 524280

File #00019 name=C:\MOVIE1\BDMV\STREAM\00040.m2ts
Duration: 00:00:34.284
start-time: 524280
Marks: 01:15:28.231

File #00020 name=C:\MOVIE1\BDMV\STREAM\00051.m2ts
Duration: 00:00:20.478
start-time: 524280

File #00021 name=C:\MOVIE1\BDMV\STREAM\00043.m2ts
Duration: 00:00:19.769
start-time: 524280

File #00022 name=C:\MOVIE1\BDMV\STREAM\00052.m2ts
Duration: 00:13:48.661
start-time: 524280
Marks: 01:19:25.093 01:23:30.129 01:25:34.462 01:28:18.334

File #00023 name=C:\MOVIE1\BDMV\STREAM\00046.m2ts
Duration: 00:00:18.977
start-time: 524280

File #00024 name=C:\MOVIE1\BDMV\STREAM\00053.m2ts
Duration: 00:00:48.882
start-time: 524280

File #00025 name=C:\MOVIE1\BDMV\STREAM\00056.m2ts
Duration: 00:00:22.063
start-time: 524280

File #00026 name=C:\MOVIE1\BDMV\STREAM\00054.m2ts
Duration: 00:00:42.542
start-time: 524280
Marks: 01:32:39.011

File #00027 name=C:\MOVIE1\BDMV\STREAM\00059.m2ts
Duration: 00:00:40.123
start-time: 524280

File #00028 name=C:\MOVIE1\BDMV\STREAM\00055.m2ts
Duration: 00:07:27.029
start-time: 524280
Marks: 01:35:41.443 01:38:49.715

File #00029 name=C:\MOVIE1\BDMV\STREAM\00062.m2ts
Duration: 00:00:56.514
start-time: 524280
Marks: 01:40:54.673

File #00030 name=C:\MOVIE1\BDMV\STREAM\00065.m2ts
Duration: 00:08:45.816
start-time: 524280
Marks: 01:42:58.964 01:50:33.126
```

After patch:
```
File #00000 name=C:\MOVIE1\BDMV\STREAM\00027.m2ts
Start time: 00:00:00.000
Duration:   00:00:55.054
Marks:      00:00:00.000

File #00001 name=C:\MOVIE1\BDMV\STREAM\00028.m2ts
Start time: 00:00:55.054
Duration:   00:00:58.099
Marks:      00:01:16.201

File #00002 name=C:\MOVIE1\BDMV\STREAM\00000.m2ts
Start time: 00:01:53.154
Duration:   00:06:03.237
Marks:      00:06:29.430

File #00003 name=C:\MOVIE1\BDMV\STREAM\00001.m2ts
Start time: 00:07:56.392
Duration:   00:00:53.136

File #00004 name=C:\MOVIE1\BDMV\STREAM\00002.m2ts
Start time: 00:08:49.528
Duration:   00:01:19.829
Marks:      00:09:22.895

File #00005 name=C:\MOVIE1\BDMV\STREAM\00005.m2ts
Start time: 00:10:09.358
Duration:   00:00:19.811

File #00006 name=C:\MOVIE1\BDMV\STREAM\00008.m2ts
Start time: 00:10:29.170
Duration:   00:00:28.903

File #00007 name=C:\MOVIE1\BDMV\STREAM\00009.m2ts
Start time: 00:10:58.073
Duration:   00:00:25.984
Marks:      00:10:58.073

File #00008 name=C:\MOVIE1\BDMV\STREAM\00012.m2ts
Start time: 00:11:24.058
Duration:   00:00:24.649

File #00009 name=C:\MOVIE1\BDMV\STREAM\00013.m2ts
Start time: 00:11:48.707
Duration:   00:00:21.646

File #00010 name=C:\MOVIE1\BDMV\STREAM\00016.m2ts
Start time: 00:12:10.354
Duration:   00:01:20.622

File #00011 name=C:\MOVIE1\BDMV\STREAM\00018.m2ts
Start time: 00:13:30.976
Duration:   00:00:37.662
Marks:      00:13:30.976

File #00012 name=C:\MOVIE1\BDMV\STREAM\00021.m2ts
Start time: 00:14:08.639
Duration:   00:28:00.136
Marks:      00:17:40.017  00:19:37.551  00:24:48.320  00:28:55.233  00:33:05.066
Marks:      00:38:13.416  00:40:33.138

File #00013 name=C:\MOVIE1\BDMV\STREAM\00017.m2ts
Start time: 00:42:08.776
Duration:   00:00:18.935

File #00014 name=C:\MOVIE1\BDMV\STREAM\00033.m2ts
Start time: 00:42:27.711
Duration:   00:26:22.831
Marks:      00:44:11.231  00:46:59.316  00:51:27.667  00:57:02.168  00:59:32.318
Marks:      01:00:53.524  01:07:19.743

File #00015 name=C:\MOVIE1\BDMV\STREAM\00034.m2ts
Start time: 01:08:50.542
Duration:   00:00:24.566

File #00016 name=C:\MOVIE1\BDMV\STREAM\00049.m2ts
Start time: 01:09:15.109
Duration:   00:02:42.912
Marks:      01:11:25.656

File #00017 name=C:\MOVIE1\BDMV\STREAM\00037.m2ts
Start time: 01:11:58.021
Duration:   00:01:26.878

File #00018 name=C:\MOVIE1\BDMV\STREAM\00050.m2ts
Start time: 01:13:24.900
Duration:   00:02:03.331

File #00019 name=C:\MOVIE1\BDMV\STREAM\00040.m2ts
Start time: 01:15:28.231
Duration:   00:00:34.284
Marks:      01:15:28.231

File #00020 name=C:\MOVIE1\BDMV\STREAM\00051.m2ts
Start time: 01:16:02.516
Duration:   00:00:20.478

File #00021 name=C:\MOVIE1\BDMV\STREAM\00043.m2ts
Start time: 01:16:22.994
Duration:   00:00:19.769

File #00022 name=C:\MOVIE1\BDMV\STREAM\00052.m2ts
Start time: 01:16:42.764
Duration:   00:13:48.661
Marks:      01:19:25.093  01:23:30.129  01:25:34.462  01:28:18.334

File #00023 name=C:\MOVIE1\BDMV\STREAM\00046.m2ts
Start time: 01:30:31.425
Duration:   00:00:18.977

File #00024 name=C:\MOVIE1\BDMV\STREAM\00053.m2ts
Start time: 01:30:50.403
Duration:   00:00:48.882

File #00025 name=C:\MOVIE1\BDMV\STREAM\00056.m2ts
Start time: 01:31:39.285
Duration:   00:00:22.063

File #00026 name=C:\MOVIE1\BDMV\STREAM\00054.m2ts
Start time: 01:32:01.348
Duration:   00:00:42.542
Marks:      01:32:39.011

File #00027 name=C:\MOVIE1\BDMV\STREAM\00059.m2ts
Start time: 01:32:43.891
Duration:   00:00:40.123

File #00028 name=C:\MOVIE1\BDMV\STREAM\00055.m2ts
Start time: 01:33:24.014
Duration:   00:07:27.029
Marks:      01:35:41.443  01:38:49.715

File #00029 name=C:\MOVIE1\BDMV\STREAM\00062.m2ts
Start time: 01:40:51.044
Duration:   00:00:56.514
Marks:      01:40:54.673

File #00030 name=C:\MOVIE1\BDMV\STREAM\00065.m2ts
Start time: 01:41:47.559
Duration:   00:08:45.816
Marks:      01:42:58.964  01:50:33.126
```

### CODE REVIEW

**Comment by justdan96** [comment]
Should we use sprintf to align output strings? Or is that a little overkill?

**Comment by jcdr428** [comment]
@justdan96 IMHO yes, overkill ;)

**Comment by xavery** [comment]
Changing any output of the main tsMuxeR binary also requires changing the GUI, since it parses the output and uses it to fill all the necessary GUI elements.

**Comment by justdan96** [comment]
Can we isolate out the lines of code where it parses console output, maybe add some easily-searchable comments? I'm just thinking maybe we can get a definitive list of "can't change" items and they can act as points of reference for any future changes, such as using a library. 

The GUI has a lot of things that are... less than optimal to me. Maybe we need a list of TODOs for that?

**Comment by jcdr428** [comment]
@xavery you're right, we have to keep allowing people still on WinXP to use tsMuxer.
In which case, do we really need the latest version of Qt5 ? Why not using a former version eg 5.3 fully compatible with XP, that would allow the XP users to use the new features (BD version 3 for AVC, select default audio or subtitle track, select angle, etc.) ?

**Comment by xavery** [comment]
@jcdr428 *If* we decide to support running newer GUIs on Windows XP, we'd have to dial the used Qt version down to 5.6, according to [this supposedly (according to the giant note at the top) outdated page](https://wiki.qt.io/PlatformSupport). If we want to support running the GUI on CPUs without SSE2, the last usable version would be 5.2.1, as the first build using SSE2 unconditionally was 5.3.0.

This isn't a problem by itself : in fact, I've downloaded the official 5.2.1 release for Linux and compiled the code after removing usages of the `QOverload` template (which I introduced myself), which was itself introduced in Qt 5.7. I'll probably merge these changes as soon as I finish writing this, since they don't really do any harm to anyone (except maybe using the member function pointer syntax, which isn't really visible everyday in today's C++ code and thus may not be as readable) and the GUI works normally.

I don't see any point in limiting all nightly builds to Qt 5.2.1, though. At most, we could just use it in 32-bit builds so that the 32-bit package is compatible all the way back to Windows XP with non-SSE2 CPUs, which means it would probably even work on the Pentium 3 collecting dust in my closet.

@justdan96 The code reading the output of the main tsMuxeR binary in stream detection mode is mostly limited to `TsMuxerWindow::onTsMuxerCodecInfoReceived()`, which parses the lines output by the binary and converts them to appropriate `QtvCodecInfo` structures which are then later used to fill the GUI elements. It's usually just enough to search the token that one is replacing in the main binary's output to find it used in the GUI without much hassle : however, this is one more thing to remember when doing changes.

**Comment by justdan96** [comment]
I'm surprised so many people requested being able to use tsMuxer with Windows XP.  Considering it went out of support 6 years ago you would hope those systems aren't connected to the internet! Seriously though what is the reasonable cut off point for what we should be supporting?

To the point at hand, since this PR can break existing functionality should we park it until the library functions for tsMuxer can be exposed?

**Comment by xavery** [comment]
> Seriously though what is the reasonable cut off point for what we should be supporting?

As a corporate programmer, I'm married to the idea of keeping everything backwards compatible to everything else - as you may have already noticed. I think our userbase is so limited that it's worth it to take the effort of providing a WinXP-non-SSE2 build as long as there are people potentially using it. The only real question is the effort needed : at any rate, it would require compiling Qt 5.2.1 manually as a static build in the MXE32 environment, integrating it into the existing Docker image, and then changing the MXE32 build script to use the 5.2.1 installation. We wouldn't be able to use the official builds anyway, since they only provide dynamically-loaded libraries. Doesn't sound like a lot, and it's a one-time thing : however, since I don't know almost anything about Docker except the fact that it exists, I have no idea about the actual effort that would be needed.

> To the point at hand, since this PR can break existing functionality should we park it until the library functions for tsMuxer can be exposed?

I'd say so. Just to clarify : introducing an actual API to the main binary (actually, more of an ABI) comes with its own set of issues, but would certainly allow reducing a lot of string parsing. The only thing that I dislike about the current approach is the fact that the tokens used in the main binary and the GUI are totally unrelated to themselves at code level : introducing an actual structured format (like JSON I mentioned before) with shared "interop" classes/structures between CLI and GUI (`nlohmann::json` allows doing just that) would certainly help here.

**Comment by jcdr428** [comment]
@justdan96 @xavery ok so let's forget about this enhancement for the moment. Improving lisibility of console output is not essential...

However at one point we have to decide what is more important, improving the software including look and feel, or keeping compatibility with an outdated OS.

**Comment by justdan96** [comment]
I do agree with that. I was thinking about creating some issues for discussing the future of some of the complex problems we'll have to overcome, so we can throw ideas around freely.

**Pull request closed without merging**
