### PR TITLE
Investigate building the project natively on MacOS

### PR DESCRIPTION
**Pull request by xavery**
This PR is here to play around with GitHub's MacOS-based runners. Inspired by #138.

### CODE REVIEW

**Comment by justdan96** [comment]
I didn't know jurplel/install-qt-action existed - it could potentially simplify _all_ our runners, right?

**Comment by xavery** [comment]
Yes and no. That action is only capable of downloading the official Qt releases, which only provide shared libraries. If we want to stick to using static linking in nightly builds, I don't think it's possible to make use of this action at all, except maybe for per-commit or per-PR builds.
What I want to investigate here is creating a .dmg by using [`macdeployqt`](https://doc-snapshots.qt.io/qt5-5.9/osx-deployment.html) that Alexey mentioned in #138, and possibly turning on Retina support so the application looks nicer.

**Comment by clout4sad** [comment]
what is the inital commit to that started this issue

**Comment by xavery** [comment]
> what is the inital commit to that started this issue

What do you mean?

**Comment by clout4sad** [comment]
an old api was opened on my network and i was told to shut it down

**Comment by xavery** [comment]
Sorry, I have no idea what you're going on about.

**Comment by clout4sad** [comment]
it said it was an mozia webpage from 2003

**Comment by moderndeveloperllc** [comment]
@xavery Does it look like this might make it into the next point release? It looks like a worthy addition.

**Comment by xavery** [comment]
I think this can be considered ready. The build still works properly after making the latest changes, and running the application in my macOS VM shows that it works okay, mostly with regards to multilanguage support, as this was probably one of the most user-visible changes in the past months.
However, the build is dynamically linked, so it probably won't be directly usable as a bintray download if we want to stick to providing static builds. Furthermore, the download is significantly larger, as this version weights 28.3 MB, while today's bintray release is only 11.38 MB.
I'm still confident that it's worthwhile to merge this, especially due to the benefit of the pull request checks, as compiling on macOS (or, more precisely, clang with the macOS platform headers), has revealed issues in the past.

If nobody has any objections, I'm going to merge this in a couple of days.

**Comment by moderndeveloperllc** [comment]
@xavery A couple of things I noticed with the artifact available from the 25th - https://github.com/justdan96/tsMuxer/actions/runs/87881264

a) The execute bit is not set on either the CLI file or tsMuxerGUI.app/Contents/MacOS/tsMuxerGUI which prevents the respective apps from starting up.
b) Was this supposed to include the Retina display fixes? I"m not seeing those.

I am seeing that the GUI is using the system light/dark system setting which is quite nice. FYI, my system is macOS 10.15.4 (19E287).

**Comment by moderndeveloperllc** [comment]
@xavery Been following your commits. https://github.com/justdan96/tsMuxer/pull/145/commits/b06cb3814b799774f37b2870c871804bfa801427 got Retina working.

**Comment by xavery** [comment]
@moderndeveloperllc Cool, thanks! I have to admit that I'm totally unfamiliar with the macOS ecosystem. My VM is running Catalina, and that commit caused Finder to display an error saying that the application "cannot be executed", because `defaults` changes the format of the `plist` file to a binary one, while it's apparently supposed to be saved in XML. This can be solved by running `plutil` to convert the file appropriately.
Could you advise on the best way to package the build? I've also run into the permissions issues you've mentioned. Will a simple `tar` be okay, or is there something macOS-specific that should be done as well?

**Comment by moderndeveloperllc** [comment]
@xavery I not an application developer myself, but I think moving the plist writes before the `macqtdelploy` is a good idea. This will allow the use of [`-codesign`](https://doc.qt.io/qt-5/macos-deployment.html#the-mac-deployment-tool) in the future - if @justdan96 ever wants to pay for an Apple Developer membership ($99/yr). Right now, even with the below changes, users will need to go to Security & Privacy and allow the GUI app to run. Only a signed app will fix that. Oh, and I would target 10.13. According to [the build logs](https://github.com/justdan96/tsMuxer/runs/623499185?check_suite_focus=true), it looks like most of the QT plugins target that version now. ex.: `2020-04-27 18:29:07,828 - aqt - INFO - Finish installation of qtspeech-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z in 0.749413607000001`. Not really necessary I guess, but 10.12 and below is no longer supported, and 10.13 came out over 2 yrs ago. The below works on my machine at least - 10.15.

New file:
```
#!/usr/bin/env bash

set -x
set -e

export MACOSX_DEPLOYMENT_TARGET=10.13

brew install pkg-config
brew install freetype
brew install zlib

builddir=$PWD

mkdir -p bin/mac
mkdir -p build

pushd build
cmake -DCMAKE_BUILD_TYPE=Release -DTSMUXER_GUI=TRUE ..
make

pushd tsMuxerGUI
defaults write "$PWD/tsMuxerGUI.app/Contents/Info.plist" NSPrincipalClass -string NSApplication
defaults write "$PWD/tsMuxerGUI.app/Contents/Info.plist" NSHighResolutionCapable -string True
plutil -convert xml1 "$PWD/tsMuxerGUI.app/Contents/Info.plist"
popd

chmod +x tsMuxer/tsmuxer
chmod +x tsMuxerGUI/tsMuxerGUI.app/Contents/MacOS/tsMuxerGUI
macdeployqt tsMuxerGUI/tsMuxerGUI.app

mv tsMuxer/tsmuxer "${builddir}/bin/mac/tsMuxeR"
mv tsMuxerGUI/tsMuxerGUI.app "${builddir}/bin/mac"
popd
```

FYI, Github has the ability to upload an Apple Code Signing certificate to integrate into the workflow:

*Github Signing Action* - https://github.com/marketplace/actions/import-code-signing-certificates

**Comment by xavery** [comment]
Thanks for the advice. I don't know why, but I was sure that `Info.plist` was created by `macdeployqt`, but a quick search reveals that it's actually CMake.
I'm not worried about the fact that this application is labelled as "downloaded from the Internet", and I really doubt if any of us is willing to pay money to distribute an application that we earn absolutely nothing from. That is, of course, unless somebody's so bothered by its "insecurity" that they're willing to fund the membership. :-)
Anyhow, I'll make the necessary changes soon. I'm assuming that packaging this into a `tar` is fine so that the proper permissions are preserved.

**Comment by justdan96** [comment]
$99 a year? I think we can do without! 😆

**Comment by moderndeveloperllc** [comment]
@xavery Yeh. Flipping the plist changes around doesn't hurt, and it's one less potential issue in the future if anyone does care. A .tgz file should preserve the permissions just fine.

@justdan96 Oh I know. But maybe some deep-pockets someday will care and pay for one! Stranger things have happened. BTW, thanks for taking over the repo and getting all the changes in. Not having to have a Windows VM to do UHD burning work is awesome. I've been able to use Handbrake (with a few custom x265 params) and tsMuxer to burn UHD disks that work great on my Sony UBP-X800M2.

**Comment by moderndeveloperllc** [comment]
@xavery, @justdan96  I was able to download and start the build artifact. It opened up, but as soon as I tried to add a file to mux, it gave me a "tsMuxer not found!" error. The nightly build doesn't have this error.

**Pull request merged**
